arq:
  client:
    address:
      host: localhost
      port: 21017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hexagonal